[package]
name    = "meshok"
version = "0.0.1"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows = "0.19"
